### ISSUE TITLE
Modification to handle wasm build

### ISSUE THREAD

**Issue by schungx** [alvinhochun/rhai-playground#21]
Since `ahash` changed its features set structure, more stuff is required in order to compile for wasm.

```toml
[dependencies]
rhai = { version = "1.10.0", default-features = false, features = [ "only_i64", "no_optimize", "internals", "wasm-bindgen" ] }

# getrandom/js must be added manually to make sure it compiles since ahash/runtime-rng requires a random number source
getrandom = { version = "0.2", features = ["js"] }
```

I'm fixing some of these inconsistencies with the upcoming release, but there doesn't seem to be a way to avoid setting `default-features = false` so it is breaking for wasm builds.
